version: "3"

services:
  django_app:
    build: .
    volumes:
      - static:/code/core/static
      - .:/code
    
  nginx:
    image: nginx:1.23.1
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
    depends_on:
      - django_app

volumes:
  .:
  static: